# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'progressBarCircular.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(528, 459)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(213, 213, 213);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.progressbar = QtWidgets.QFrame(self.frame)
        self.progressbar.setGeometry(QtCore.QRect(110, 60, 300, 300))
        self.progressbar.setMinimumSize(QtCore.QSize(300, 300))
        self.progressbar.setStyleSheet("QFrame{\n"
"border-radius: 150px;\n"
"background-color: qconicalgradient(cx:0.5, cy:0.5, angle:90, stop: {stop1}  rgba(255, 0, 0, 0), stop:{stop2} rgba(255, 0, 95, 255));\n"
"\n"
"\n"
"\n"
"}")
        self.progressbar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.progressbar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.progressbar.setObjectName("progressbar")
        self.circulo = QtWidgets.QFrame(self.progressbar)
        self.circulo.setGeometry(QtCore.QRect(20, 20, 260, 260))
        self.circulo.setMinimumSize(QtCore.QSize(260, 260))
        self.circulo.setStyleSheet("QFrame{\n"
"    \n"
"    background-color: rgb(0, 0, 255);\n"
"   border-radius: 130px;\n"
"\n"
"\n"
"}")
        self.circulo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.circulo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.circulo.setObjectName("circulo")
        self.voltaje = QtWidgets.QLabel(self.circulo)
        self.voltaje.setGeometry(QtCore.QRect(51, 100, 111, 68))
        self.voltaje.setStyleSheet("font: 85 36pt \"Arial \";\n"
"color: rgb(255, 255, 255);")
        self.voltaje.setAlignment(QtCore.Qt.AlignCenter)
        self.voltaje.setObjectName("voltaje")
        self.label_2 = QtWidgets.QLabel(self.circulo)
        self.label_2.setGeometry(QtCore.QRect(170, 100, 37, 68))
        self.label_2.setStyleSheet("font: 85 36pt \"Arial \";\n"
"color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.circulo)
        self.label.setGeometry(QtCore.QRect(60, 190, 141, 20))
        self.label.setStyleSheet("font: 63 12pt \"Segoe UI Semibold\";\n"
"color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.actualizar = QtWidgets.QPushButton(self.frame)
        self.actualizar.setGeometry(QtCore.QRect(220, 30, 75, 23))
        self.actualizar.setStyleSheet("QPushButton{\n"
"border:3px solid  rgb(0, 0, 255);\n"
"font: 87 9pt \"Arial Black\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border:3px solid  rgb(255, 0, 0);\n"
"font: 87 9pt \"Arial Black\";\n"
"}\n"
"")
        self.actualizar.setObjectName("actualizar")
        self.layoutWidget = QtWidgets.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 390, 511, 28))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.desconectar = QtWidgets.QPushButton(self.layoutWidget)
        self.desconectar.setStyleSheet("background-color: rgb(170, 0, 255);\n"
"font: 87 9pt \"Arial Black\";")
        self.desconectar.setObjectName("desconectar")
        self.horizontalLayout.addWidget(self.desconectar)
        self.conectar = QtWidgets.QPushButton(self.layoutWidget)
        self.conectar.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"font: 87 9pt \"Arial Black\";")
        self.conectar.setObjectName("conectar")
        self.horizontalLayout.addWidget(self.conectar)
        self.puertos = QtWidgets.QComboBox(self.layoutWidget)
        self.puertos.setObjectName("puertos")
        self.horizontalLayout.addWidget(self.puertos)
        self.velocidad = QtWidgets.QComboBox(self.layoutWidget)
        self.velocidad.setObjectName("velocidad")
        self.horizontalLayout.addWidget(self.velocidad)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ProgressBarCircular con Arduino"))
        self.voltaje.setText(_translate("MainWindow", "5.0"))
        self.label_2.setText(_translate("MainWindow", "V"))
        self.label.setText(_translate("MainWindow", "VOLTAJE ARDUINO"))
        self.actualizar.setText(_translate("MainWindow", "Iniciar"))
        self.desconectar.setText(_translate("MainWindow", "DESCONECTAR"))
        self.conectar.setText(_translate("MainWindow", "CONECTAR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
